#!/bin/bash

# Print commands
set -x

# Generate apache vhost conf if not exist
if [ ! -s "$FILE_CONF_VHOST" ]; then    
    bash "$FILE_GENERATE_CONF_VHOST_SH" > "$FILE_CONF_VHOST"
fi

# Apache gets grumpy about PID files pre-existing
rm -f $PATH_VAR_APACHE/apache2.pid

# Start apache
apachectl -d /etc/apache2/ -e info

# Start varnish
$EXEC_VARNISH > "$FILE_LOG_VARNISH" &
PID_VARNISH="$!"

# Make sure that log files exists
touch "$FILE_LOG_APACHE_ACCESS"
touch "$FILE_LOG_APACHE_ERROR"

# Tail logs to stdout
exec tail -f "$FILE_LOG_VARNISH" "$FILE_LOG_APACHE_ACCESS" "$FILE_LOG_APACHE_ERROR" &

# Fail if any subprocesses exit
wait -n
exit 1
